data:
  root: '/mnt/ceph/users/jfeather/data/training_datasets_audio/JSIN_all_v3/subsets/'

audio_rep:                                  # Attributes of audio feature
  name: 'cochleagram_1_1_5_secs'
  on_gpu: True

audio_transforms:
  low_snr: 3
  high_snr: 10
  dbspl: 60
  crop: 'RandomCropForegroundBackground'
  crop_kwrgs:
    signal_size: 40000        # signal size in frames
    crop_length: 30000 

val_metric: 'val_class_prec_epoch'
val_metric_mode: 'max'

module: LitAudioSetSSL

hparas:                                   # Experiment hyper-parameters
  epochs: 10                              # Each "epoch" is 25 passes through the speech dataset
  global_batch_size: 512                 # set global batch size as init. Will be divided by n gpus and task params
  optimizer: "LARS"
  lr: 0.4                                # initial LR 
  lambda_ssl: 1
  valid_step: 5000
  ssl_task: 'audioset'                            # either 'word', 'audioset', 'dual'
  ssl_loss_str: 'barlow'
  ssl_loss: 'Barlow_Loss'
  ssl_loss_kwargs:
    lmbda: 0.01
    out_dim: 1024
    

model:                                    # Model architecture
  arch_name: "SSLBaseModel"
  arch_kwargs:
    backbone: 'resnet18'
    in_channels: 1
    projector_dims: [8192, 1024]
    proj_out_dim: 512
    num_classes: 517
    supervised: True
    