audio_rep:
  name: cochleagram_1
  on_gpu: true
audio_transforms:
  dbspl: 60
  high_snr: 10
  low_snr: -10
data:
  dataset: MatchedAudiosetBatched
  noise_h5_path: ${COCHDNN_AUDIOSET_TRAIN_H5}
  blocked_batches: true
  signal_augment: true
  target_keys:
  - noise/labels_int
  val_noise_h5_path: ${COCHDNN_AUDIONOISE_VALID_H5}
  val_speech_h5_path: ${COCHDNN_JSIN_VALID_H5}
hparas:
  epochs: 100
  global_batch_size: 640
  lambda_ssl: 1
  lr: 0.2
  num_warmup_steps_or_ratio: 0.1
  optimizer: LARS
  ssl_loss: Paired_Loss
  ssl_loss_kwargs:
    lmda: 0.0
    loss_fn_eq: Barlow_Loss
    loss_fn_eq_kwargs:
      lmbda: 0.01
      out_dim: 512
    loss_fn_inv: Barlow_Loss
    loss_fn_inv_kwargs:
      lmbda: 0.01
      out_dim: 512
  ssl_loss_str: paired
  ssl_task: dual
  task_loss_params:
    noise/labels_int:
      loss_type: bcewithlogitsloss
      weight: 1.0
  valid_step: 5000
model:
  arch_kwargs:
    backbone: kell2018
    in_channels: 1
    num_classes:
      noise/labels_int: 527
    proj_out_dim: 4096
    projector_dims:
    - 512
    - 512
    supervised: true
  arch_name: SSLBaseModelDualTask
val_metric:
  audioset_task: val_noise/labels_int_prec
val_metric_mode: max
