audio_rep:
  name: cochleagram_1
  on_gpu: true
audio_transforms:
  dbspl: 60
  high_snr: 10
  low_snr: -10
data:
  blocked_batches: true
  dataset: MatchedSpeechInNoiseDatasetBatched
  noise_h5_path: /mnt/home/jfeather/ceph/data/training_datasets_audio/audioset_dataframes/sr20000/cullLabels_silence/sr20000_unbalanced_train_segments_raw_exclude_speech_and_only_music_maxZerosPercent10.pdh5
  signal_augment: true
  skip_aug_match: false
  speech_h5_path: /mnt/home/jfeather/ceph/data/training_datasets_audio/jsinV3BalancedProcessed/sr_20000/splits/train_stackedDataframeHDF_n150_VJRUH4IEPDGPNH2JZMULSQKOWYNQ6KMM.pdh5
  target_keys:
  - signal/word_int
  - signal/speaker_int
  - noise/labels_int
  val_noise_h5_path: /mnt/home/jfeather/ceph/data/training_datasets_audio/audioset_dataframes/sr20000/cullLabels_silence/sr20000_balanced_train_segments_raw_exclude_speech_and_only_music_maxZerosPercent10.pdh5
  val_speech_h5_path: /mnt/home/jfeather/ceph/data/training_datasets_audio/jsinV3BalancedProcessed/sr_20000/splits/valid_stackedDataframeHDF_n150_VJRUH4IEPDGPNH2JZMULSQKOWYNQ6KMM.pdh5
hparas:
  epochs: 100
  global_batch_size: 512
  lambda_ssl: 1
  lr: 0.2
  num_warmup_steps_or_ratio: 0.1
  optimizer: LARS
  ssl_loss: Paired_Loss
  ssl_loss_kwargs:
    lmda: 0.5
    loss_fn_eq: Barlow_Loss
    loss_fn_eq_kwargs:
      lmbda: 0.01
      out_dim: 512
    loss_fn_inv: Barlow_Loss
    loss_fn_inv_kwargs:
      lmbda: 0.01
      out_dim: 512
  ssl_loss_str: paired
  ssl_task: dual
  task_loss_params:
    noise/labels_int:
      loss_type: bcewithlogitsloss
      weight: 1.0
    signal/speaker_int:
      loss_type: crossentropyloss
      weight: 1.0
    signal/word_int:
      loss_type: crossentropyloss
      weight: 1.0
  valid_step: 5000
model:
  arch_kwargs:
    backbone: resnet18
    in_channels: 1
    no_avgpool: true
    num_classes:
      noise/labels_int: 517
      signal/speaker_int: 433
      signal/word_int: 794
    proj_out_dim: 46592
    projector_dims:
    - 512
    - 512
    supervised: true
  arch_name: SSLBaseModelDualTask
val_metric:
  audioset_task: val_noise/labels_int_prec
  speaker_task: val_signal/speaker_int_acc
  word_task: val_signal/word_int_acc
val_metric_mode: max
