name: cochdnn_ssl_pl
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - lightning
  - torchmetrics
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - h5py
  - pytables
  - matplotlib
  - jupyter
  - ipykernel
  - tqdm
  - pyyaml
  - requests
  - resampy
  - ffmpeg
  - sox
  - libsndfile
  - pip:
      - cox
      - datasets
      - dill
      - openai-whisper
      - soundfile
      - tensorboardX
      - timm
      - transformers
      - chcochleagram @ git+https://github.com/jenellefeather/chcochleagram.git
