data:
  dataset: MatchedAudiosetBatched
  noise_h5_path: '${COCHDNN_AUDIOSET_TRAIN_H5}'
  val_speech_h5_path: '${COCHDNN_JSIN_VALID_H5}'
  val_noise_h5_path: '${COCHDNN_AUDIONOISE_VALID_H5}'
  target_keys: ['noise/labels_int']
  blocked_batches: true
  signal_augment: true
  skip_aug_match: false
  in_sample_rate: 16000
  out_sample_rate: 20000

audio_rep:
  name: 'cochleagram_1'
  on_gpu: True

audio_transforms:
  low_snr: -10
  high_snr: 10
  dbspl: 60

val_metric:
  audioset_task: 'val_noise/labels_int_acc'

hparas:
  epochs: 100
  batch_size: 192
  global_batch_size: 768
  optimizer: "LARS"
  num_warmup_steps_or_ratio: 0.01
  lr: 0.2
  valid_step: 5000
  task_loss_params:
    noise/labels_int:
      loss_type: 'bcewithlogitsloss'
      weight: 300.0

model:
  arch_name: "kell2018_multi_task"
  arch_params:
    num_classes:
      noise/labels_int: 527
    pretrained: False

