data:
  speech_h5_path: '/mnt/home/jfeather/ceph/data/training_datasets_audio/jsinV3BalancedProcessed/sr_20000/splits/train_stackedDataframeHDF_n150_VJRUH4IEPDGPNH2JZMULSQKOWYNQ6KMM.pdh5'
  noise_h5_path: '/mnt/home/jfeather/ceph/data/training_datasets_audio/audioset_dataframes/sr20000/cullLabels_silence/sr20000_unbalanced_train_segments_raw_exclude_speech_and_only_music_maxZerosPercent10.pdh5' 
  val_speech_h5_path: '/mnt/home/jfeather/ceph/data/training_datasets_audio/jsinV3BalancedProcessed/sr_20000/splits/valid_stackedDataframeHDF_n150_VJRUH4IEPDGPNH2JZMULSQKOWYNQ6KMM.pdh5'
  val_noise_h5_path: '/mnt/home/jfeather/ceph/data/training_datasets_audio/audioset_dataframes/sr20000/cullLabels_silence/sr20000_balanced_train_segments_raw_exclude_speech_and_only_music_maxZerosPercent10.pdh5' 
  dataset: MatchedSpeechInNoiseDatasetBatched
  target_keys: ['signal/word_int']
  blocked_batches: True

audio_rep:                                  # Attributes of audio feature
  name: 'cochleagram_1'
  on_gpu: True

audio_transforms:
  low_snr: -10
  high_snr: 10
  dbspl: 60

val_metric:
    word_task: 'val_signal/word_int_acc'

hparas:                                   # Experiment hyper-parameters
  epochs: 100                              
  batch_size: 192                          # using Matched dataset - true global batch size is 4x this (e.g. 768 if 192)
  global_batch_size: 768                  # Use true global batch size for LARS initial LR calc 
  optimizer: "LARS"
  num_warmup_steps_or_ratio: 0.01
  lr: 0.2                                 # base LR for LARS
  valid_step: 5000
  task_loss_params:
    signal/word_int:
      loss_type: 'crossentropyloss'
      weight: 1 

model:                                    # Model architecture
  arch_name: "resnet_multi_task18"
  arch_params:
    num_classes:
      signal/word_int: 794               # TODO: -1 from this if not using null
    pretrained: False