audio_rep:
  name: cochleagram_1
  on_gpu: true
audio_transforms:
  dbspl: 60
  high_snr: 10
  low_snr: -10
data:
  root: /mnt/ceph/users/jfeather/data/training_datasets_audio/JSIN_all_v3/subsets/
hparas:
  epochs: 10
  global_batch_size: 768
  lambda_ssl: 1
  lr: 0.2
  num_warmup_steps_or_ratio: 0.1
  optimizer: LARS
  ssl_loss: MMCR_Loss
  ssl_loss_str: mmcr
  ssl_task: word
  valid_step: 5000
lr: 0.6
model:
  arch_kwargs:
    n_classes: 794
    proj_out_dim: 2048
    projector_dims:
    - 8192
    - 2048
    supervised: true
  arch_name: SSLAudioModelWMetamers
